# Generated by Django 3.1.2 on 2020-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://lh3.googleusercontent.com/proxy/3slo6vQK0O5jchXrrArp1JocMXYyiGBZvFDwdd7hNfzOm0yvi9tnB9VDO4jEnvpXV3LOINboqWeKbiqxqtvFaAIgs7B5NmiCULF3DQ7mzNVQcnM5Obc8tD164xOk', max_length=500),
        ),
    ]
