# Generated by Django 3.1.2 on 2020-11-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://pronto-core-cdn.prontomarketing.com/448/wp-content/uploads/sites/2/2019/06/food-placeholder-600x314.jpg', max_length=500),
        ),
    ]
